### ISSUE TITLE
Expose single `flow()` function in API instead of `flow()`/`flowMax()`?

### ISSUE THREAD

**Issue by mattpetrie** [helixbass/ad-hok#40]
Since the eslint plugin has a rule that will catch unnecessary uses of `flowMax()` or uses of `flow()` that *should* be `flowMax()`, I'm assuming it's possible to programmatically determine whether it's necessary or not for a given composition chain to use `flowMax()`. 

If that's the case, rather than the user having to make a determination of which one to use, it would be awesome to expose a single `flow()` function as the API, and then determine which function to use "under the hood".  This would reduce the mental overhead of needing to determine which function is appropriate each time one is needed, and would also eliminate having to go back and change a `flow()` to `flowMax()` or vice versa if the chain it wraps changes.

What I'm imagining here is essentially a `flowMax()` that falls back to lodash `flow()` when `flowMax()` isn't necessary, but I think sticking with the name `flow()` is both shorter and more intuitive for its use.

**Comment by helixbass** [comment]
> Since the eslint plugin has a rule that will catch unnecessary uses of `flowMax()` or uses of `flow()` that should be `flowMax()`, I'm assuming it's possible to programmatically determine whether it's necessary or not for a given composition chain to use `flowMax()`

The ESLint plugin doesn't know strictly in which cases `flowMax()` is required - when using "secondary named helpers" (eg `addShouldShowFirstDepositFlow`), it doesn't know whether those helpers contain magic `ad-hok` helpers (in which case `flowMax()` would be required) or not

So the ESLint plugin exposes a "conservative" might-need-`flowMax()` rule ([`prefer-flowmax`](https://github.com/helixbass/eslint-plugin-ad-hok/blob/master/docs/rules/prefer-flowmax.md)) as well as a more "liberal" definitely-needs-`flowMax()` rule ([`needs-flowmax`](https://github.com/helixbass/eslint-plugin-ad-hok/blob/master/docs/rules/needs-flowmax.md))

> If that's the case, rather than the user having to make a determination of which one to use, it would be awesome to expose a single `flow()` function as the API, and then determine which function to use "under the hood"

So a couple factors at play here:

My general response here is that to avoid needing to think about `flow()` vs `flowMax()`, you can just always use `flowMax()` (there's nothing wrong with using it even when not necessary, it shouldn't incur any performance penalty or anything)

The reason I don't tend to do that is because (a) for some reason I find it aesthetically/conceptually appealing to use `flow()` when it suffices (b) I never have to think about or manually toggle between using `flow()` vs `flowMax()` because of my ESLint setup - by using `"ad-hok/should-fix-flow-flowmax": true` + `eslint-plugin-known-imports` + running ESLint in fix mode in my editor, I just always write `flow()` and ESLint will auto-change it to `flowMax()` for me when it decides it might be necessary as well as update the `flow`/`flowMax` imports as needed

But if you don't/can't have your editor set up that way, then I'd agree it's not worth the mental overhead of thinking about the two options and I'd recommend just always using `flowMax()` (eg that's what they're doing on Swiss Life where they're using Typescript so don't have known-imports running)

We can discuss if that's the case for our current project

In terms of "why bother explaining/exposing `flow()` vs `flowMax()` at all?", that's a valid question as it presents the possibility for confusion when learning `ad-hok` (Alex had similar feedback). I like the idea that for people already familiar with the semantics of lodash/fp `flow()`, it's conceptually helpful to realize that typically what you're doing is just simple function composition (and then also potentially helpful to grasp that there are things that require "magic" that simple function composition can't achieve). But I could potentially be convinced that it's better to only present `flowMax()` (not `flow()`) in the docs (and possibly correspondingly update the types of things the ESLint plugin exposes)

In terms of the naming of the helper exposed by `ad-hok`, I think it's better to avoid confusion that it's interchangeable with lodash/fp `flow()` so stick with a different name - I like `flowMax()` since to me it expresses "this is lodash/fp `flow()` plus some other stuff". And when using known-imports it's nice to avoid "import namespace overlaps" when possible (so that it knows what I mean when I use `flow()`)

**Comment by peterstuart** [comment]
> The reason I don't tend to do that is because (a) for some reason I find it aesthetically/conceptually appealing to use flow() when it suffices

Me too—using `flowMax` when it's not necessary breaks my personal "don't use a more powerful function/abstraction than necessary" style rule. That said, I do think the default advice in the docs should be "always use flowMax". Understanding the difference between `flow`/`flowMax` seems like an unnecessary hurdle to getting into `ad-hok`, with no practical benefit.

**Comment by helixbass** [comment]
Ok I'm on board with suppressing `flow()` vs `flowMax()`-awareness in the docs given that both of you and @amay have all expressed that opinion

So opened #48 as a TODO to update the docs
